# Generated by Django 4.0.2 on 2022-02-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadersmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
